# Generated by Django 2.0.2 on 2018-02-15 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VoteHandler', '0002_auto_20180214_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='can_id',
            field=models.UUIDField(unique=True, verbose_name='Smartcan ID'),
        ),
        migrations.AlterField(
            model_name='disposable',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
