# Generated by Django 2.0.2 on 2018-02-12 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VoteHandler', '0002_auto_20180211_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disposables',
            name='msg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='VoteHandler.WarningMessage'),
        ),
        migrations.AlterField(
            model_name='materials',
            name='material',
            field=models.CharField(default={}, max_length=100),
            preserve_default=False,
        ),
    ]
