# Generated by Django 2.0.2 on 2018-02-12 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VoteHandler', '0004_auto_20180211_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disposables',
            name='msg',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='VoteHandler.WarningMessage'),
        ),
    ]
