# Generated by Django 2.0.2 on 2018-02-12 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VoteHandler', '0006_auto_20180211_2252'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Disposables',
            new_name='Disposable',
        ),
        migrations.RenameModel(
            old_name='Materials',
            new_name='Material',
        ),
    ]
