# Generated by Django 2.0.2 on 2018-03-08 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('VoteHandler', '0004_auto_20180307_2302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin_num', models.CharField(max_length=15)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VoteHandler.Category')),
            ],
        ),
        migrations.CreateModel(
            name='CanInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_id', models.UUIDField(unique=True, verbose_name='Smartcan ID')),
                ('channel_name', models.CharField(max_length=255, null=True)),
                ('config', models.TextField(max_length=4096)),
            ],
        ),
        migrations.AddField(
            model_name='bin',
            name='sId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Config.CanInfo'),
        ),
    ]
