# Generated by Django 2.0.2 on 2018-05-27 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VoteHandler', '0004_auto_20180307_2302'),
        ('Config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caninfo',
            name='default_bin',
            field=models.ForeignKey(default=19, on_delete=django.db.models.deletion.CASCADE, to='VoteHandler.Category'),
        ),
        migrations.AlterField(
            model_name='bin',
            name='bin_num',
            field=models.IntegerField(),
        ),
    ]
