# Generated by Django 2.0.2 on 2018-05-28 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Config', '0002_auto_20180527_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caninfo',
            old_name='default_bin',
            new_name='default_category',
        ),
    ]
